-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        kb_layout = "us,tr,ara",
        numlock_by_default = true,
        touchpad = {
            drag_lock = 0,
        },
    },
})

-- Bezier curves
hl.curve("standard", { type = "bezier", points = { {0.2, 0.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 8.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.0,
    bezier = "standard",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@165.00Hz",
    position = "0x0",
    scale = 1.33,
    cm = "srgb",
})
